### ISSUE TITLE
Package copy-anything that replaced lodash.cloneDeep doesn't play well with expo.

### ISSUE THREAD

**Issue by mikealche** [blitz-js/superjson#190]
As the title says, https://github.com/blitz-js/superjson/commit/882febac4b3113e3aa771d7ceca993a604cbcff5 added the package `copy-anything`. 

Unfortunately this package doesn't play well with expo. 
```
While trying to resolve module `copy-anything` from file `/Users/mike/batcave/movida/apps/mobile/node_modules/superjson/dist/index.js`, the package `/Users/mike/batcave/movida/node_modules/copy-anything/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/mike/batcave/movida/node_modules/copy-anything/dist/index.cjs`. Indeed, none of these files exist:

  * /Users/mike/batcave/movida/node_modules/copy-anything/dist/index.cjs(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * /Users/mike/batcave/movida/node_modules/copy-anything/dist/index.cjs/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * 
 ```

![image](https://user-images.githubusercontent.com/8585011/169663469-15bdf6d8-bd54-4e76-ac99-545f9b9a75c8.png)

I can always roll back to a previous version, but I thought it might be worthwhile going back to the old package for the main branch of superjson.

**Comment by Baira** [comment]
It is also the case for a base react-native project

**Comment by Skn0tt** [comment]
Interesting! I'll open an issue in `copy-anything`, and see what their maintainer thinks. If it's fixable, I'd be happy to stick with `copy-anything`.

**Comment by Skn0tt** [comment]
@Baira @mikealche can you check if https://github.com/react-navigation/react-navigation/issues/7003#issuecomment-579746569 helps you?

**Comment by Baira** [comment]
@Skn0tt Sorry this didn't help. It still says :

````
Error: While trying to resolve module `copy-anything` from file `C:\projects\xxxxx\node_modules\superjson\dist\index.js`, the package `C:\projects\xxxxx\node_modules\copy-anything\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`C:\projects\xxxxx\node_modules\copy-anything\dist\index.cjs`. Indeed, none of these files exist:
````

**Comment by Skn0tt** [comment]
Cool cool! Then I'll go ahead and close this.

**Comment by mattrabe** [comment]
To clarify on @Baira's metro.config.js solution:

That solution does work for me. But the included comment states `// add tsx if its not yet defined`, which seems misleading. In my case it was "cjs" that was missing - not "tsx". I suspect "cjs" to be the true culprit, since error message states `could not be resolved (C:\projects\xxxxx\node_modules\copy-anything\dist\index.cjs`

Here is what I ended up with in metro.config.js. Thanks @Baira!

```
const { getDefaultConfig } = require('expo/metro-config')

module.exports = (() => {
  const config = getDefaultConfig(__dirname)

  return {
    ...config,
    resolver: {
      ...config.resolver,
      sourceExts: [
        ...config.resolver.sourceExts,
        'cjs',
      ],
    },
  }
})
```

**Comment by rcaraway101** [comment]
@Baira where do you add that exactly ?

my `metro.config.js` file looks something like this.

```ts
// Learn more https://docs.expo.dev/guides/monorepos
const { getDefaultConfig } = require("expo/metro-config")
const path = require("path")

// Find the project and workspace directories
// eslint-disable-next-line no-undef
const projectRoot = __dirname
// This can be replaced with `find-yarn-workspace-root`
const workspaceRoot = path.resolve(projectRoot, "../..")

const config = getDefaultConfig(projectRoot)

// 1. Watch all files within the monorepo
config.watchFolders = [workspaceRoot]
// 2. Let Metro know where to resolve packages and in what order
config.resolver.nodeModulesPaths = [
  path.resolve(projectRoot, "node_modules"),
  path.resolve(workspaceRoot, "node_modules"),
]
// 3. Force Metro to resolve (sub)dependencies only from the `nodeModulesPaths`
config.resolver.disableHierarchicalLookup = true

module.exports = config
```

**Comment by a-eid** [comment]
@rcaraway101 

adding this line should fix it for you.

`config.resolver.sourceExts = [...config.resolver.sourceExts, "cjs"]`

**Comment by rcaraway101** [comment]
that works for you.

**Comment by marinoandrea** [comment]
Hi, I am still experiencing issues with `copy-anything`, using `@trpc/react-query` and `yarn` workspaces. I am posting this here because I believe it is unrelated to the `trpc` stack, since dropping `superjson` as a transformer fixes the problem (but it may have something to do with my `yarn` monorepo setup?).

I have tried the solution proposed here and, while I can confirm that `copy-anything` is indeed in my root `node_modules` folder featuring a `.cjs` module, I still get the following error:

```
[TRPCClientError: copy_anything_1.copy is not a function. (In 'copy_anything_1.copy(json)', 'copy_anything_1.copy' is undefined)]
``` 

The import itself seems to work but the functions inside the module are undefined.
Besides the following:

```js
// metro.config.js

const { createMetroConfiguration } = require("expo-yarn-workspaces");

const config = createMetroConfiguration(__dirname);

config.resolver.assetExts.push("cjs");
config.resolver.sourceExts.push("cjs"); 

module.exports = config;
```

I have also tried including the source extensions in my Babel configuration without success:

```js
// babel.config.js

module.exports = function (api) {
  api.cache(true);
  return {
    presets: ["babel-preset-expo"],
    plugins: [
      [
        "module-resolver",
        {
          extensions: [".ios.js", ".android.js", ".js", ".jsx", ".ts", ".tsx", ".json", ".cjs"],
          ...
```

Can anyone provide some insight on what is going on here?

**Comment by skyriverbend** [comment]
`config.resolver.sourceExts.push('cjs')` also works
